{{- if .Values.rateOracle.env.secret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: {{ .Chart.Name }}
stringData:
  {{- range $key, $value := .Values.rateOracle.env.secret }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}