version: '3'

services:
  mysql:
    image: mysql:5.7.25
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./provision:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - casper-local

volumes:
  mysql-data:
    driver: local

networks:
  casper-local:
