rateOracle:
    env:
        secret:
            TEST_SECRET: ENC[AES256_GCM,data:99isCQ==,iv:aoZOvQUZgori19IDYB1+FxEI5zbi/8hJw1JIPVgYQV8=,tag:V5rOwexUclQfJRTu80Y2dw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:494750395663:key/f4b90c09-7359-4049-83b5-8581b169642a
          created_at: "2023-12-03T22:44:36Z"
          enc: AQICAHhv0TxxQyXM+XdBxU+kbxak7CcF3/swUDTfXfG1B2tp2AGFwOlDar66SKThvV1wjD8SAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW8qGR3R6UIiJobu/AgEQgDt2xqEprnI1Uu9XYxtF/6QFy3+DMnLIqLN2acGjwXgLwBsLIgrcbwgcWhcaRy7jTmFKlTI+D82P2xsEKw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-03T22:44:36Z"
    mac: ENC[AES256_GCM,data:rPfCq4Hhhv5dnVuMNSN8L1zz+ZMjhn/4my3lJsbRP4eJABWenOnMrlSy87a5a1jxxbceIG7Yjbd1EBEWHMCvcV5r+VZX89/eG5/wl1KKA0XCexsAPQZmc6BA0VjOuZ0sIQ23ZcOWPJzAa3NwX2GmOUYeQv+Iz6+8V9qXMeBENnk=,iv:mJigyR/OIc6xL6NkEoSTQK1UT5YEnmqh0gcvVowg+5g=,tag:1783Et5nmmhdsmmvfsGXjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
