name: (DEV) Build and deploy all images

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repository: RATE_ORACLE
            dockerfile: rate-oracle.dockerfile
          - repository: CRDAO_API
            dockerfile: api.dockerfile
          - repository: CRDAO_HANDLER
            dockerfile: handler.dockerfile

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets[format('ECR_REPOSITORY_{0}', matrix.repository)] }}
        tags: |
          type=sha
          type=raw,value=latest

    - name: Build and push up
      uses: docker/build-push-action@v5
      with:
        file: infra/docker/${{ matrix.dockerfile }}
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
